// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdq9zqLsE4pfQFFiLdU2EfW7mQUuG1OA',
    appId: '1:873723497999:web:6cdb5f558df7764fa01d7a',
    messagingSenderId: '873723497999',
    projectId: 'abdiessaie',
    authDomain: 'abdiessaie.firebaseapp.com',
    storageBucket: 'abdiessaie.appspot.com',
    measurementId: 'G-6DPYBE50N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-8r1V29iD_utS_w0Qm7h_b5RqOnNp4RU',
    appId: '1:873723497999:android:ca7286328e038f40a01d7a',
    messagingSenderId: '873723497999',
    projectId: 'abdiessaie',
    storageBucket: 'abdiessaie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwKzyskMSoqvlPypGft0LGrL6JHNHcip4',
    appId: '1:873723497999:ios:e57961738fc2910ea01d7a',
    messagingSenderId: '873723497999',
    projectId: 'abdiessaie',
    storageBucket: 'abdiessaie.appspot.com',
    iosClientId: '873723497999-k7t1r7acm4dtmc0viu8v8a2liv5g24c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.abdi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwKzyskMSoqvlPypGft0LGrL6JHNHcip4',
    appId: '1:873723497999:ios:a1779cbf5c83cb57a01d7a',
    messagingSenderId: '873723497999',
    projectId: 'abdiessaie',
    storageBucket: 'abdiessaie.appspot.com',
    iosClientId: '873723497999-pp8ejp3rf8th466kb05ni7m7ukc89ghp.apps.googleusercontent.com',
    iosBundleId: 'com.example.abdi.RunnerTests',
  );
}
